name: Workflow Run

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  avisa-sobre-termino-do-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Informa o nome do curso
        run: echo "O Workflow Compartilhado 'Build' terminou de ser executado"