name: Teste Lacerda

on:
    push:
        branches:
            - main

jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: vERIFICAR SO
              run: cat /etc/os-release

            - name: Mostrar que deu certo
              run: echo 'DEU CERTO'

